### ISSUE TITLE
PV reduction of tensor integral coefficient functions

### ISSUE THREAD

**Issue by apik** [FeynCalc/feyncalc#13]
Looks like there is something wrong with PV reduction of tensor integral coefficient functions when compared with the same functions calculated with LoopTools directly, here is a code sample:

```
toLT = {FeynCalc`PaVe[0, {}, {mm_}] -> LoopTools`A0[mm], 
   FeynCalc`PaVe[0, 0, {}, {mm}] -> LoopTools`A00[mm], 
   FeynCalc`C0[a___] -> LoopTools`C0[a], 
   FeynCalc`B0[a___] -> LoopTools`B0[a], 
   FeynCalc`A0[a___] -> LoopTools`A0[a], 
   FeynCalc`PaVe[x___] -> LoopTools`PaVe[x]};

tests = {
   TEST[0, {3}, {1, 2}],
   TEST[0, 0, {3}, {1, 2}],
   TEST[1, 1, {3}, {1, 2}],
   TEST[0, {1}, {1, 1}],
   TEST[0, 0, {1}, {1, 1}],
   TEST[1, 1, {1}, {1, 1}]
   };

Print["FA: ", 
    SeriesCoefficient[# /. 
        TEST[x___] -> FeynCalc`PaVe[x, PaVeAutoReduce -> True] /. 
       toLT /. D -> 4 - 2 ep, {ep, 0, 0}], 
    " LT:", # /. TEST[x___] -> LoopTools`PaVe[x]] & /@ tests;
```

and its output:

**FA: 0.0569409 LT:0.0569409**

FA: 0.136399 LT:0.469732

FA: 0.041684 LT:-0.0694271

**FA: 0.186201 LT:0.186201**

FA: 0.213217 LT:0.490995

FA: 0.333333 LT:0.0555556

**Comment by vsht** [comment]
Hi Andrey,

actually, both the results of FeynCalc and LoopTools are fully correct. The
reason, why you see the discrepancy, is that your comparison code is not ok.

You have to consider that LoopTools returns you only the finite part of the 
integral, subtracting the singularity, Euler Gamma and a Log of pi. 

Since the FeynCalc results depend on D and you to want to expand around 4-2 ep,
you need to reintroduce the singularity, since otherwise you would loose finite
parts from ```(1/ep)*(ep*x)```.

Here is a code that does that (including a small fix for LoopTools' PaVe to handle
A functions properly)

```
Block[{$ContextPath}, BeginPackage["LoopTools`"];
  Install[
   "/home/vs/.Mathematica/Applications/looptools-mirror/x86_64-Linux/\
bin/LoopTools"];
  EndPackage[];
  ];
<< FeynCalc`

LTPaVe[i__Integer, {p___}, {m__}] := (ToExpression[
       "LoopTools`" <> #1 <> "0i"][
      ToExpression["LoopTools`" <> #2 <> #2 <> ToString /@ Sort[{i}]],
       p, m] &)[FromCharacterCode[Length[{m}] + 64], 
   FromCharacterCode[Length[{m}] + 96]];

LTGetUVAndFinal[args__] :=
  (LoopTools`SetLambda[-1]; 
   uvpart = LTPaVe[args]; LoopTools`SetLambda[0];
   LTPaVe[args] + uvpart (1./ep - EulerGamma - Log[Pi]));
   
tests = {TEST[0, {3}, {1, 2}], TEST[0, 0, {3}, {1, 2}], 
   TEST[1, 1, {3}, {1, 2}], TEST[0, {1}, {1, 1}], 
   TEST[0, 0, {1}, {1, 1}], TEST[1, 1, {1}, {1, 1}]};
   
   
Print["FA: ", 
    Normal@Series[# /. 
         TEST[x___] :> 
          ToPaVe2[PaVe[x, PaVeAutoReduce -> True]] /. {PaVe -> 
          LTGetUVAndFinal} /. D -> 4 - 2 ep, {ep, 0, 0}], 
    " LT:", # /. TEST[x___] :> Expand[LTGetUVAndFinal[x]]] & /@ tests;   
```

and the output

```
FA: 1./ep-1.665 LT:1./ep-1.665

FA: 0.5/ep-0.391241 LT:0.5/ep-0.391241

FA: 0.333333/ep-0.643409 LT:0.333333/ep-0.643409

FA: 1./ep-1.53574 LT:1./ep-1.53574

FA: 0.416667/ep-0.226483 LT:0.416667/ep-0.226483

FA: 0.333333/ep-0.518426 LT:0.333333/ep-0.518426
```
P.S. Just for completeness, here are the analytic results for the for above integrals obtained with H.Patel's Package-X

```
testInts = {Epsilon^(-1) + (6 - 3*EulerGamma - Sqrt[2]*Pi - 
      2*Log[2] - 3*Log[Pi] + 3*Log[ScaleMu^2])/3, 
  1/(2*Epsilon) + (57 - 27*EulerGamma - 4*Sqrt[2]*Pi - 20*Log[2] - 
      27*Log[Pi] + 27*Log[ScaleMu^2])/54, 
  1/(3*Epsilon) + (21 - 27*EulerGamma - Sqrt[2]*Pi - 32*Log[2] - 
      27*Log[Pi] + 27*Log[ScaleMu^2])/81, 
  Epsilon^(-1) + (6 - 3*EulerGamma - Sqrt[3]*Pi - 3*Log[Pi] + 
      3*Log[ScaleMu^2])/3, 
  5/(12*Epsilon) + (34 - 15*EulerGamma - 3*Sqrt[3]*Pi - 15*Log[Pi] + 
      15*Log[ScaleMu^2])/36, 
  1/(3*Epsilon) + (1 - 6*EulerGamma - 6*Log[Pi] + 6*Log[ScaleMu^2])/
    18}

```    
   
P.P.S. When doing such comparisons, extra care is needed for C- and D- coefficient functions, where for sufficiently high ranks one might encounter both UV and IR divergences.

P.P.P.S Thanks to @t-hahn for the tip with SetLambda, since I'm not very familiar with LoopTools.

Hope this helps.

Cheers,
Vladyslav

**Comment by apik** [comment]
Vladislav, you are right and thank you for the trick with SetLambda!
