### ISSUE TITLE
Bug for FourDivergence

### ISSUE THREAD

**Issue by QSSRHelper** [FeynCalc/feyncalc#161]
```12.1.1  Windows (64-bit)```
  ```9.3.1```
  ```No```
  ```(** User Mathematica initialization file **)``` 

```FourDivergence[FAD[{q}].GSD[q].SUNT[colb].FourDivergence[GSD[q].FAD[{q}],FVD[q, lorc]], FVD[q, lora]]```
The T^colb not appear in the dot product as it should be.

**Comment by vsht** [comment]
I see no reason, why the color matrix should remain inside the dot product. It clearly commutes with the Dirac matrices,
so it should be pulled out of the Dirac string to enable further simplifications. This is actually the standard behavior of
`DotSimplify` since ever:
```
GA[i1, i2] . SUNT[a] . GA[i3] . SUNT[b] . GA[i4] . SUNT[c] // DotSimplify
(*SUNT[a] . SUNT[b] . SUNT[c]*GA[i1] . GA[i2] . GA[i3] . GA[i4]*)
```
Notice that the relative ordering of the color matrices w.r.t. each other is preserved as it should.

Is there any use case where one wants a color matrix to be kept inside the Dirac chain?

**Comment by vsht** [comment]
Since there was no reaction for 2 weeks, I'm closing this one for the time being.
