### ISSUE TITLE
PaVeReduce Problem

### ISSUE THREAD

**Issue by Teddym0913** [FeynCalc/feyncalc#29]
*  <summary>Your Mathematica version</summary>    

 9.0 for Mac OS X x86 (64-bit) (February 13, 2013)

*  <summary>Your FeynCalc version</summary>    

  9.2.0

*  <summary>Did you try to reinstall FeynCalc (stable version) using the automatic installer to make sure that you have the latest bugfixes?</summary>    

 Yes, the FeynCalc is installed using the automatic installer just yesterday.

*  <summary>Please provide a minimal working example that illustrates the problem. Please explain the difference between the current behavior and the expected behavior.</summary>    

- Current behavior:
```
In[]:= A0[m1]
Out[]= m1 B0[0, m1, m1]
```
- expected behavior:
```
In[]:= A0[m1]
Out[]= m1 + m1 B0[0, m1, m1]
```
Have not yet checked other function carefully. Maybe also has some problem with B1 or B11.

**Comment by vsht** [comment]
The result given by FeynCalc, i.e.

```
-((2 m^2 PaVe[0, {0}, {m^2, m^2}])/(2 - D))
```

 is correct:

$LoadAddOns = {"FeynHelpers"};
<< FeynCalc`

A0[m^2] // PaXEvaluate
PaVeReduce[A0[m^2], A0ToB0 -> True] // PaXEvaluate

gives 

m^2/Epsilon - m^2 (-1 + EulerGamma - Log[ScaleMu^2/(m^2 \[Pi])])

in both cases. In case you naively did

PaVeReduce[A0[m^2], A0ToB0 -> True] /. D -> 4

then no wonder you got something nonsensical, since after this replacement the finite part of the integral is not correct anymore.

**Comment by Teddym0913** [comment]
Thanks for explanation. I just move from History version to the new one, I will look into that and I fount the FAQ page talking about the this. Thanks!

**Comment by vsht** [comment]
You can still set `$LimitTo4` to `True` to get the old behavior, but I would rather use new methods to avoid it. With `FeynHelpers` you can easily obtain the full singularity structure with UV and IR divergences nicely separated for almost any 1-loop integral. In the upcoming FeynCalc 9.3 (i.e. the current development version) there is also a function PaVeUVPart (c.f. https://feyncalc.org/forum/1287.html) that will give you the UV singularity of any scalar 1-loop integral. So for renormalization purposes in MS schemes you would not even need `FeynHelpers`. I currently see no scenartio where would really be forced to use "$LimitTo4". Especially, since with it one can easily make mistakes and end up with a wrong finite part.
