### ISSUE TITLE
conflict between FeynCalc and FeynRules 

### ISSUE THREAD

**Issue by BenjaminDbb** [FeynCalc/feyncalc#32]
*  <summary>Mathematica version</summary>    

  ```Mathematica 11.2.0.0```

*  <summary>FeynCalc version</summary>    

  ```FeynCalc 9.2.0. FeynArts 3.1 patched for use with FeynCalc. FeynHelpers 1.1.0 loaded```
  ``` FeynRules 2.3.32```

When I use them
```
FR$Parallel = False;
$FeynRulesPath = SetDirectory[$UserBaseDirectory <> "/Applications/FeynRules"];
<< FeynRules`;

(* Not important*)
```
and 
```
$LoadAddOns = {"FeynHelpers"};
$LoadFeynArts = True;
<< FeynCalc`;
$FAVerbose = 0;

(* Not important*)
```
I have to call ```Quit[]``` to restart the kernel before use the package, otherwise 
```
Symbol *** appears in multiple contexts {FeynCalc`,FeynRules`}; definitions in context FeynCalc` may shadow or be shadowed by other definitions.
```
I wonder if there exists conflict  between FeynCalc 9.2.0 and FeynRules 2.3.32, or FeynArts 3.1 patched in FeynCalc has already patched FeynRules? If patched, how to call it?
Thank you

**Comment by vsht** [comment]
Hi,
this is expected, since FeynRules and FeynCalc are not supposed to be loaded on the same kernel!

First you run FeynRules, create your model and export it to FeynArts. Then you restart the kernel, load FeynCalc and patched FeynArts, patch the model and do your calculations. The example files for FeynHelpers follow exactly this strategy. There is no reason to have FeynRules and FeynCalc running simultaneously.
