### ISSUE TITLE
Equation of Motion

### ISSUE THREAD

**Issue by mescia** [FeynCalc/feyncalc#5]
The instruction DiracSimplify[ Spinor[p1, m1].(DiracSlash[p2]).DiracMatrix[7].Spinor[p2, m2]] produces the following worng result 
-(m2*Spinor[Momentum[p1], m1, 1] . Spinor[Momentum[p2], m2, 1])/2 - 
  m2*Spinor[Momentum[p1], m1, 1] . DiracGamma[5] . Spinor[Momentum[p2], m2, 1]
1/2 is missing. FeynCal v8.2 produces the right result.
I am using mathemetica 9, linux or windows. thanks.

**Comment by vsht** [comment]
Thanks for the bug report. The issue was a wrong definition of DiracGamma[6] and DiracGamma[7] in Anti5. Since I usually prefer to write out the chiral projectors explicitly as 1/2 +- 1/2 GA[5], this bug somehow never occured to me.

It is now fixed also in the stable branch, just rerun the automatic installer and overwrite the existing installation.
