### ISSUE TITLE
BUG about trasversality of the polarization vector

### ISSUE THREAD

**Issue by mescia** [FeynCalc/feyncalc#6]
neither SP[k, Polarization[k, I]]  neither Pair[ Momentum[k], Momentum[ Polarization[k, I] ] ] are vanishing in feynCalc 9 (mathematica 9 ).

**Comment by vsht** [comment]
This is in fact not a bug. Polarization vectors are not automatically transverse since FeynCalc 9, as written in the changelog:

https://github.com/FeynCalc/feyncalc/blob/master/FeynCalc/Changelog.md

The point is that with automatic transversality, calculations with massive vector bosons are very inconvenient. You can now either set the transversality property for each vector separately

`SP[k, Polarization[k, I, Transversality -> True]]`

or activate it globally (for all polarization vectors), which would mimic the behavior of previous FeynCalc versions
```

SetOptions[Polarization, Transversality -> True];
SP[k, Polarization[k, I]]
```

**Comment by Dayve89** [comment]
The two commands you stated work for SP[k,Polarization[k,I]] but do not enable automatic transversality for PolarizationVector function. I have to explicitly make use of complex polarization vectors and there seems not to be a way out of this. please help

**Comment by vsht** [comment]
Why?


SetOptions[Polarization, Transversality -> True];

PolarizationVector[p, mu] FV[p, mu] // Contract

gives 0, no?


Am 19.10.2016 um 10:34 schrieb Dayve89:

**Comment by Dayve89** [comment]
I'm new to FeynCalc and 

SetOptions[Polarization, Transversality -> True];

PolarizationVector[p, mu] FV[p, mu] // Contract

gives zero but not if I define:

epsilon[mu_]=PolarizationVector[p, mu];
p[mu_]=FV[p,mu]

and make

ScalarProduct[epsilon,p]

after having switched transversality on

**Comment by vsht** [comment]
ScalarProduct[p, Polarization[p, I]]

evaluates to

Pair[Momentum[p], Momentum[Polarization[p, I]]]

while your ScalarProduct[epsilon, p] gives

Pair[Momentum[epsilon], Momentum[p]]

which is obviously different and not equivalent.

So the simple solution is not to introduce extra
abbreviations on top of FeynCalc`s abbreviations,
unless you very well understand what you
are doing. Otherwise you will run into issues like this...



Am 19.10.2016 um 12:05 schrieb Dayve89:

**Comment by Dayve89** [comment]
thanks for your comment, in fact i found it more convenient to define the polarization vector as an ordinary FV and easily specified it's properties manually. thanks for your help anyway!
