### ISSUE TITLE
DoPolarizationSums

### ISSUE THREAD

**Issue by keith-hamilton** [FeynCalc/feyncalc#8]
Hi feyncalc, 
I wanted to ask if the behaviour below is intended for DoPolarizationSums. The 'non-commutativity' I am seeing of DoPolarizationSums and the Lorentz index contraction operations easily caught me out. So long as I carry out all polarisation sums first with contract->false and only afterwards contract the final result, I get an answer I like. Note in D=4 there is no issue.
Cheers, Keith.
P.S. I like this function.

ScalarProduct[p1, p1] = 0;
ScalarProduct[p2, p2] = 0;
testExpression = 
  Pair[LorentzIndex[\[Alpha]1, D], 
    Momentum[Polarization[p1, I, Transversality -> True], D]] Pair[
    LorentzIndex[\[Alpha]1, D], 
    Momentum[Polarization[p1, -I, Transversality -> True], D]] Pair[
    LorentzIndex[\[Alpha]2, D], 
    Momentum[Polarization[p2, I, Transversality -> True], D]] Pair[
    LorentzIndex[\[Alpha]2, D], 
    Momentum[Polarization[p2, -I, Transversality -> True], D]];

DoPolarizationSums[DoPolarizationSums[testExpression, p1, n], p2, n]
DoPolarizationSums[
  DoPolarizationSums[testExpression, p1, n, Contract -> False], p2, n,
   Contract -> False] // Contract

First return value is 2D-4 , the second is (D-2)^2 .

**Comment by vsht** [comment]
Hi,
thanks for reporting this issue. As you might have noticed, 
the problem occurs only for D - dimensional polarization vectors, 
while in the D -> 4 limit both expressions are equal.
    
The handling of D-dimensional polarization vectors is still not very well tested, as
it is a quite new feature that was not available before FeynCalc 9.

In this particular case there was an issue with the 

eps^mu (lambda) eps_mu (lambda) = -1

relation which is true only in 4 dimensions.
  
Anyhow, this issue should be now fixed with both expressions
returning the same. 

The fix goes to the development version, although FeynCalc 9.0.3 
that incorporates all the current enhancements and fixes should be
released soon.

**Comment by keith-hamilton** [comment]
Thanks Vladyslav!

Cheers, Keith.
